version: '3.4'

services:
  app:
    build:
      context: ./posterr-api
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - ./posterr-api:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: ./posterr-api/.env
    environment:
      RAILS_ENV: development
  database:
    image: postgres:12.1
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./posterr-api/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  gem_cache:
  db_data: